config:
  target: "http://127.0.0.1:9090"
  phases:
    - duration: 60
      arrivalRate: 5
  plugins:
    publish-metrics:
      - type: prometheus
        pushgateway: "http://127.0.0.1:9091"
        tags:
          - "testId:prometheus_test"
          - "type:loadtest"
scenarios:
  - name: "prometheus-load-test"
    flow:
      - get:
          url: "/metrics"
          headers:
            accept: "text/plain"
      - think: 1
