global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "prometheus"
    honor_labels: true
    static_configs:
      - targets: ["prometheus:9090"]
        labels:
          alias: 'prometheus'

  - job_name: "cadvisor"
    honor_labels: true
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          alias: 'cadvisor'