global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "prometheus"
    honor_labels: true
    static_configs:
      - targets: ["prometheus:9090"]
        labels:
          alias: 'prometheus'

  - job_name: "cadvisor"
    honor_labels: true
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          alias: 'cadvisor'

  - job_name: "grafana"
    honor_labels: true
    static_configs:
      - targets: ["grafana:3000"]
        labels:
          alias: 'grafana'
  
  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
        labels:
          alias: 'pushgateway'