global:
  scrape_interval: 30s 

scrape_configs:

  - job_name: "prometheus"
    honor_labels: true
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "cadvisor"
    honor_labels: true
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]