#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <script_name>"
    exit 1
fi

SCRIPT_NAME=$1
PROYECT_DIR="$(dirname "$(readlink -f "$0")")"
ARTILLERY_DIR="${PROYECT_DIR}/artillery"
SCRIPTS_DIR="${ARTILLERY_DIR}/scripts"
PAYLOADS_DIR="${ARTILLERY_DIR}/payloads"
PROCESSORS_DIR="${ARTILLERY_DIR}/processors"

echo "Running script: $1"

docker run --rm -it \
    --volume ${SCRIPTS_DIR}:/scripts:ro \
    --volume ${PAYLOADS_DIR}:/payloads:ro \
    --volume ${PROCESSORS_DIR}:/processors:ro \
    --network host \
    artilleryio/artillery:2.0.0-31 \
    run /scripts/$SCRIPT_NAME
