#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <script_name>"
    exit 1
fi

SCRIPT_NAME=$1
PROYECT_DIR="$(dirname "$(readlink -f "$0")")"
ARTILLERY_DIR="${PROYECT_DIR}/artillery"

DOCKER_SCRIPTS_DIR="/scripts"

echo "Running script: $1"

docker run --rm -it \
    --volume ${ARTILLERY_DIR}:/scripts:ro \
    --network host \
    artilleryio/artillery:2.0.0-31 \
    run /scripts/$SCRIPT_NAME
