[package]
name = "dataset-manager"
version = "0.1.0"
authors = ["Mario Rojas"]
about = "A tool to manage datasets"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
